services:
  insightface-api:
    image: debian:bullseye-slim
    working_dir: /app
    command: >
      bash -c "
      apt-get update &&
      apt-get install -y python3 python3-pip python3-dev libglib2.0-0 libsm6 libxext6 libxrender-dev libgomp1 libgl1-mesa-glx wget curl &&
      ln -sf /usr/bin/python3 /usr/bin/python &&
      ln -sf /usr/bin/pip3 /usr/bin/pip &&
      pip install --no-cache-dir -r requirements.txt &&
      mkdir -p ~/.insightface/models &&
      python app.py
      "
    expose:
      - "5000"
    environment:
      - PORT=5000
      - PYTHONUNBUFFERED=1
      - DEBIAN_FRONTEND=noninteractive
    volumes:
      - .:/app
      - models_data:/root/.insightface/models
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 180s

volumes:
  models_data: