services:
  insightface-api:
    image: python:3.9-slim
    working_dir: /app
    command: >
      sh -c "
      apt-get update && 
      apt-get install -y libglib2.0-0 libsm6 libxext6 libxrender-dev libgomp1 libgl1-mesa-glx wget curl &&
      pip install --no-cache-dir -r requirements.txt &&
      mkdir -p ~/.insightface/models &&
      gunicorn --bind 0.0.0.0:5000 --workers 1 --timeout 120 app:app
      "
    expose:
      - "5000"
    environment:
      - PORT=5000
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app
      - models_data:/root/.insightface/models
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 120s

volumes:
  models_data: