services:
  insightface-api:
    # Usar registry.gitlab.com como alternativa
    image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
    working_dir: /app
    command: |
      sh -c "
        echo '🚀 Iniciando instalación de InsightFace API...' &&
        apk update &&
        apk add --no-cache python3 py3-pip python3-dev gcc musl-dev linux-headers glib-dev libsm libxext libxrender wget curl bash &&
        ln -sf /usr/bin/python3 /usr/bin/python &&
        echo '📦 Instalando dependencias Python...' &&
        pip install --no-cache-dir -r requirements.txt &&
        mkdir -p ~/.insightface/models &&
        echo '✅ Iniciando servidor...' &&
        python app.py
      "
    expose:
      - "5000"
    environment:
      PORT: 5000
      PYTHONUNBUFFERED: "1"
    volumes:
      - .:/app
      - models_data:/root/.insightface/models
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 300s

volumes:
  models_data: