services:
  insightface-api:
    image: ghcr.io/linuxserver/baseimage-ubuntu:focal
    working_dir: /app
    command: >
      bash -c "
      apt-get update && 
      apt-get install -y python3 python3-pip python3-dev libglib2.0-0 libsm6 libxext6 libxrender-dev libgomp1 libgl1-mesa-glx wget curl &&
      ln -sf /usr/bin/python3 /usr/bin/python &&
      ln -sf /usr/bin/pip3 /usr/bin/pip &&
      pip install --no-cache-dir Flask==2.3.3 opencv-python-headless==4.8.1.78 numpy==1.24.3 Pillow==10.0.1 onnxruntime==1.16.0 gunicorn==21.2.0 insightface==0.7.3 &&
      mkdir -p ~/.insightface/models &&
      gunicorn --bind 0.0.0.0:5000 --workers 1 --timeout 120 app:app
      "
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app
      - models_data:/root/.insightface/models
    restart: unless-stopped

volumes:
  models_data: