services:
  insightface-api:
    build: .
    expose:
      - "5000"
    environment:
      PORT: 5000
      PYTHONUNBUFFERED: "1"
    volumes:
      - models_data:/root/.insightface/models
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.insightface.rule=Host(`your-domain.com`)"
      - "traefik.http.services.insightface.loadbalancer.server.port=5000"

volumes:
  models_data:
    driver: local